name: Build and Test           
on:
  push:                             
    branches:
      - master                 
jobs:
  build:                   
    runs-on: ubuntu-latest
    steps:
      - name: checkout code            
        uses: actions/checkout@v2
      - name: setup JDk
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin
      - name: test                 
        run: mvn test
      - name: Package
        run: mvn clean package
      
      - name: Log in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MY_SECRET_USERNAME }}
          password: ${{ secrets.MY_SECRET_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rohitballer/wiprogithub:1.2


